before_install:
  - sudo make travis
  - make pre-build
language: cpp
script: make && make test && make quick-tests
after_success:
  - gcov-4.8 -p -r `find build -name '*.gcda'`
  - coveralls --exclude gen-ber --exclude deps --no-gcov --verbose
