before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - git submodule update --init
  - cd deps/asn1c && autoreconf -iv && ./configure && make && cd ../..
  - sudo pip install PyYAML
  - sudo pip install cpp-coveralls
language: cpp
script: make && make test && make quick-tests
after_success:
  - gcov-4.8 -p -r `find build -name '*.gcda'`
  - coveralls --exclude gen-ber --no-gcov --verbose
