before_install:
  - git submodule update --init
  - cd deps/asn1c && autoreconf -iv && ./configure && make && cd ../..
  - sudo apt-get install -y g++-4.8 
  - sudo update-alternatives
language: cpp
script: make && make test
